config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'session/new'
  root 'static_pages#home'
  get 'gotologin'    => 'static_pages#gotologin'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  get 'signup' => 'users#new'

  get 'administrator' => 'administrator#index'
  get 'administrator/new' => 'administrator#new'
  post 'administrator/create' => 'administrator#create'
  get 'administrator/delete/:id' => 'administrator#delete'
  get 'administrator/courselist' =>'administrator#courselist'
  get 'administrator/newcourse' =>'administrator#newcourse'
  post 'administrator/createcourse' =>'administrator#createcourse'
  get 'administrator/editcourse/:id' =>'administrator#editcourse'
  get 'administrator/deletecourse/:id' =>'administrator#deletecourse'
  post 'administrator/updatecourse' =>'administrator#updatecourse'
  get 'administrator/courseinstructor/:id' =>'administrator#courseinstructor'
  post 'administrator/courseinstructor/:id' =>'administrator#courseinstructoradd'
  get 'administrator/courseinstructordelete/:courseid/:instructorid' =>'administrator#courseinstructordelete'
  get 'administrator/userhistory/:id' => 'administrator#userhistory'
  get 'administrator/coursestudent/:id' =>'administrator#coursestudent'
  post 'administrator/coursestudent/:id' =>'administrator#coursestudentadd'
  get 'administrator/coursestudentdelete/:courseid/:studentid' =>'administrator#coursestudentdelete'
  get 'administrator/coursestudentgrade/:courseid/:studentid' => 'administrator#coursestudentgrade'
  post 'administrator/coursestudentgrade/:courseid/:studentid' => 'administrator#coursestudentgradeupdate'

  get 'administrator/instructorlist' =>'administrator#instructorlist'
  get 'administrator/newinstructor' =>'administrator#newinstructor'
  post 'administrator/createinstructor' => 'administrator#createinstructor'
  get 'administrator/deleteinstructor/:id' => 'administrator#deleteinstructor'

  get 'administrator/studentlist' =>'administrator#studentlist'
  get 'administrator/newstudent' =>'administrator#newstudent'
  post 'administrator/createstudent' => 'administrator#createstudent'
  get 'administrator/deletestudent/:id' => 'administrator#deletestudent'

  get 'course/coursepage/:id' => 'course#coursepage'
  post 'course/coursepage/:id' => 'course#coursenotificationadd'

  get 'instructor' => 'instructor#index'

  get 'course' => 'course#index'
  get 'mycourses' => 'course#mycourse'
  get 'course/studentcoursedrop/:id' => 'course#studentcoursedrop'
  get 'course/coursehistory' => 'course#coursehistory'

  get 'requests' => 'instructor#requests'
  get 'instructor/enroll/:user_id/:course_id'=> 'instructor#enroll'

  get 'instructor/requestinactive/:id' => 'instructor#requestinactive'
  get 'message' => 'message#index'
  get 'message/chatwindow/:id' => 'message#chatwindow'
  post 'message/chatwindow/:id' => 'message#chatwindowsend'

  get 'request/requestenroll/:course_id/:user_id' => 'request#requestenroll'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence:true
  validates :email, presence:true, uniqueness:true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :password, presence:true,
              length: {minimum: 8}
  has_secure_password

  has_and_belongs_to_many :courses
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  #def hello
  #  render text: "hello, world!"
  #end

  #def index
  #  @users = User.all
  #end

  # GET /users/1
  # GET /users/1.json
  #def show
  #  #@user=User.find(params[:id])
  #end

  # GET /users/new
  def new
    #if logged in redirect to default page here.
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.role='student'

    respond_to do |format|
      if @user.save
        flash[:success]= "Welcome #{@user.name}"
        format.html { redirect_to gotologin_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :submit, class:'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/index.html.erb
</br>
</br>
</br>
</br>

  <h1>Search Page</h1>
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered table-hover">

  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
</br>
</br>
</br>

<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>My Profile</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%if @role=='instructor'%>
  <%= link_to 'Back', instructor_path %>
<% elsif @role=='admin'%>
  <%= link_to 'Back', administrator_path %>
<% else %>
  <%= link_to 'Back', user_path %>
<%end%>