config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'session/new'
  root 'static_pages#home'
  get 'gotologin'    => 'static_pages#gotologin'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  get 'signup' => 'users#new'

  get 'administrator' => 'administrator#index'
  get 'administrator/new' => 'administrator#new'
  post 'administrator/create' => 'administrator#create'
  get 'administrator/delete/:id' => 'administrator#delete'
  get 'administrator/courselist' =>'administrator#courselist'
  get 'administrator/newcourse' =>'administrator#newcourse'
  post 'administrator/createcourse' =>'administrator#createcourse'
  get 'administrator/editcourse/:id' =>'administrator#editcourse'
  get 'administrator/deletecourse/:id' =>'administrator#deletecourse'
  post 'administrator/updatecourse' =>'administrator#updatecourse'
  get 'administrator/courseinstructor/:id' =>'administrator#courseinstructor'
  post 'administrator/courseinstructor/:id' =>'administrator#courseinstructoradd'
  get 'administrator/courseinstructordelete/:courseid/:instructorid' =>'administrator#courseinstructordelete'
  get 'administrator/userhistory/:id' => 'administrator#userhistory'
  get 'administrator/coursestudent/:id' =>'administrator#coursestudent'
  post 'administrator/coursestudent/:id' =>'administrator#coursestudentadd'
  get 'administrator/coursestudentdelete/:courseid/:studentid' =>'administrator#coursestudentdelete'
  get 'administrator/coursestudentgrade/:courseid/:studentid' => 'administrator#coursestudentgrade'
  post 'administrator/coursestudentgrade/:courseid/:studentid' => 'administrator#coursestudentgradeupdate'

  get 'administrator/instructorlist' =>'administrator#instructorlist'
  get 'administrator/newinstructor' =>'administrator#newinstructor'
  post 'administrator/createinstructor' => 'administrator#createinstructor'
  get 'administrator/deleteinstructor/:id' => 'administrator#deleteinstructor'

  get 'administrator/studentlist' =>'administrator#studentlist'
  get 'administrator/newstudent' =>'administrator#newstudent'
  post 'administrator/createstudent' => 'administrator#createstudent'
  get 'administrator/deletestudent/:id' => 'administrator#deletestudent'

  get 'course/coursepage/:id' => 'course#coursepage'
  post 'course/coursepage/:id' => 'course#coursenotificationadd'

  get 'instructor' => 'instructor#index'

  get 'course' => 'course#index'
  get 'mycourses' => 'course#mycourse'
  get 'course/studentcoursedrop/:id' => 'course#studentcoursedrop'
  get 'course/coursehistory' => 'course#coursehistory'

  get 'requests' => 'instructor#requests'
  get 'instructor/enroll/:user_id/:course_id'=> 'instructor#enroll'

  get 'instructor/requestinactive/:id' => 'instructor#requestinactive'
  get 'message' => 'message#index'
  get 'message/chatwindow/:id' => 'message#chatwindow'
  post 'message/chatwindow/:id' => 'message#chatwindowsend'

  get 'request/requestenroll/:course_id/:user_id' => 'request#requestenroll'
  resources :users

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
          <a class="navbar-brand" href="#">
            <img alt="Brand" src="https://brand.ncsu.edu/assets/logos/ncstate-brick-4x1-red-min.png">
          </a>
        </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
        <% if @role=="student" %>
          <li> <%= link_to "Search", course_path,{'style'=>'color:white'}%> </li>
          <li> <%= link_to "My Courses", mycourses_path,{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Course History", {controller: "course", action:"coursehistory"},{'style'=>'color:white'} %> </li>
          <li> <%= link_to "Messages", message_path,{'style'=>'color:white'}%> </li>


        <% elsif @role=="admin" || @role=="superadmin"%>
          <li> <%= link_to "Manage Admins", administrator_path%> </li>
          <li> <%= link_to "Manage Instructors", {controller: "administrator" ,action:"instructorlist"},{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Manage Students", {controller: "administrator" ,action:"studentlist"},{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Manage Courses", {controller: "administrator" ,action:"courselist"},{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Messages", message_path,{'style'=>'color:white'}%> </li>


        <% elsif @role=="instructor" %>
          <li> <%= link_to "Enrollment requests", requests_path,{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Courses", mycourses_path,{'style'=>'color:white'}%> </li>
          <li> <%= link_to "Messages", message_path,{'style'=>'color:white'} %> </li>
        <% end%>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle cwhite" style="color:white; background-color: #cc0000" data-toggle="dropdown">
              <%= @current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu cwhite" style="background-color: #cc0000">
              <li><%= link_to "Profile", @current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path,{'style'=>'color:white'} %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://cdn.ncsu.edu/brand-assets/fonts/include.css"
        rel="stylesheet" type="text/css" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="wrapper">
      <%= yield %>
    </div>
  </body>
</html>